#!/bin/sh

VIDEO="/root/video.mp4"
INPUT_PORT=7000
OUTPUT_PORT=6000

ffmpeg -re -stream_loop -1 -i "$VIDEO" \
    -vf "scale=640:480,fps=25" \
    -c:v libx264 -preset ultrafast -tune zerolatency \
    -x264opts keyint=25:min-keyint=10:no-scenecut \
    -an \
    -fflags nobuffer -flags low_delay -probesize 32 -analyzeduration 0 \
    -f mpegts "tcp://127.0.0.1:$INPUT_PORT?listen=1" &

FFMPEG_PID=$!

socat TCP4-LISTEN:$OUTPUT_PORT,fork TCP4:127.0.0.1:$INPUT_PORT
